# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: cff-validate

jobs:
  cff-validate:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            jsonlite
            yaml
            jsonvalidate

      - name: Validate cff
        run: |
          # Read file
          citfile <- yaml::read_yaml("CITATION.cff")

          # Convert to json
          jsonlite::write_json(citfile, "CITATION.json", pretty = TRUE)

          # Clean json file
          citfile_clean <- readLines("CITATION.json")
          citfile_clean <- gsub('["','"', citfile_clean, fixed = TRUE)
          citfile_clean <- gsub('"]','"', citfile_clean, fixed = TRUE)
          writeLines(citfile_clean, "CITATION.json")

          # Download latest scheme
          download.file("https://raw.githubusercontent.com/citation-file-format/citation-file-format/main/schema.json",
                        "schema.json", mode="wb", quiet = TRUE)


          result <- jsonvalidate::json_validate("CITATION.json",
                                      "schema.json",
                                      verbose = TRUE)

          print(result)
          if (result == FALSE){
            stop("Error on your cff file")
          }
        shell: Rscript {0}
