on:
  workflow_dispatch:

name: Test on GHA

jobs:
  test-gha:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      # This is needed for workflows running on
      # ubuntu-20.04 or later
      - name: Install V8
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y libv8-dev

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            devtools
            remotes
            tidymodels
            tidyverse
            ctv

      - name: Install core packages of all views and rOpenSci
        run: |

          install.packages("remotes", dependencies = TRUE)
          remotes::install_cran(c("ctv", "dplyr", "jsonlite"),
            dependencies = TRUE, quiet = TRUE
          )

          # Install core packages of all views
          allviews <- ctv::available.views()


          packs <- lapply(seq_len(length(allviews)), function(x) {
            allviews[[x]]$packagelist
          })

          packs <- dplyr::bind_rows(packs)
          core <- dplyr::filter(packs, core == TRUE)

          # rOpenSci packages from r-universe

          ropensci <- unlist(jsonlite::read_json("https://ropensci.r-universe.dev/packages"))

          all <- sort(unique(c(core$name, ropensci)))

          remotes::install_cran(all,
            dependencies = TRUE,
            quiet = TRUE
          )
        shell: Rscript {0}


      - name: Test GHA
        run: |

          # Load package
          devtools::load_all()

          # Delete first the snaps folder
          unlink("./tests/testthat/test_local_installation/_snaps",
          recursive = TRUE)

          # Run the tests
          testthat::test_dir("tests/testthat/test_local_installation")

        shell: Rscript {0}

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -m 'Update core test with gha' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
