# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
on:
  release:
    types: [published]
  push:
    paths:
      - DESCRIPTION
      - inst/CITATION
  workflow_dispatch:

name: Update CITATION.cff

jobs:
  update-citation-cff:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            ropensci/cffr
            V8

      - name: Update CITATION.cff
        run: |

          library(cffr)

          # Customize with your own code
          # See https://docs.ropensci.org/cffr/articles/cffr.html
          
          # Write your own keys
          mykeys <- list()

          cff_write(keys = mykeys)

        shell: Rscript {0}

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add CITATION.cff
          git commit -m 'Update CITATION.cff' || echo "No changes to commit"
          git push origin || echo "No changes to commit"



